### ISSUE TITLE
ルーティングの実装について

### ISSUE THREAD

**Issue by mizushima1226** [macmeals/todo_react_app_2#7]
一例ですが、
`http://localhost:3000/todoregister`と`http://localhost:3000/todolist/todoregister`のURLで同じ画面へ遷移できてしまいます
（他にもありそう🤔）

おそらく、
1. 画面遷移の設計ができていない
2. それに基づいて`react-router-dom`で画面遷移を実装できていない

ように見受けられます

まずは1番の画面遷移の設計を考えて、画面の階層構造を意識してみると良いと思います👍

**Comment by macmeals** [comment]
ご確認ありがとうございます🍰
以下の通り画面遷移&ルーティングを実装、見直しました。
その中で404ページを作成しました。
http://localhost:3000/　　　　　　　　　→TOPページ
http://localhost:3000/todoregister　　　→Todo登録ページ
http://localhost:3000/todolist　　　　　→TodoListページ
http://localhost:3000/*（上記以外の他のページ）　→404ページ

**Comment by mizushima1226** [comment]
修正内容確認できました！

ただ、`todoupdate/todolist`が残っていそうです💡

**Comment by macmeals** [comment]
ご確認ありがとうございます。
申し訳ありません、todoupdate.jsxの部分は別途構築する予定だったので、ルーティングは見直していませんでした・・・。以下の通り修正しました！
`export const TodoUpdateRoutes = [
  { path: "", exact: true, children: <TodoUpdate /> },
  { path: "*", exact: false, children: <Page404 /> },
]

**Comment by mizushima1226** [comment]
良きと思います〜
こちら、masterブランチ未反映でしょうか？
確認出来次第こちらのissueはcloseいたします〜
