### ISSUE TITLE
ボタンコンポーネントについて

### ISSUE THREAD

**Issue by mizushima1226** [macmeals/todo_react_app_2#8]
`TodoList`と`TodoRegister`内でそれぞれボタンコンポーネントを定義していますが、共通の部品なので`component/Button.jsx`のように共通のコンポーネントとして切り出すのが良いと思います〜

**Comment by macmeals** [comment]
ご確認ありがとうございます👍
ボタンコンポーネントを作成しました。
・Button.jsx

読み込み先に以下の通り記載しました。
`<EventButton
                clickEvent={onDeleteTodo}
                indexNumber={index}
                buttonName={"削除"}
              />`

**Comment by mizushima1226** [comment]
```
      <StyledButton
        onClick={() => {
          clickEvent(indexNumber)
        }}
      >
```
ここはシンプルにpropsでonClickを受け取ってStyledButtonのonClickに設定するだけで良いかと思います〜
（ButtonコンポーネントはindexNumberを受け取らない・意識しない）
またコンポーネントの名称も単純にButtonコンポーネントで良いかと💡
（ファイル名とexportするコンポーネント名は一致させる）

**Comment by mizushima1226** [comment]
これは好みで分かれるかもな話ですが、
buttonNameでテキストを渡しているところ、childrenとして渡してあげると直感的に使えるコンポーネントになるかと思います〜

こんな感じです↓

```
<Button>削除</Button>
```
