### ISSUE TITLE
linkstyleについて

### ISSUE THREAD

**Issue by mizushima1226** [macmeals/todo_react_app_2#9]
`linkstyle`に関するコードが２カ所で見受けられますが、`LinkText`のようなコンポーネントを作ってあげるといい感じに部品化できてReactっぽい実装になります👍

コンポーネント内でいちいちスタイルを定義する必要もなくなるので可読性もかなり上がると思います〜

**Comment by macmeals** [comment]
コメントありがとうございます☕️
LinkTextコンポーネントを作ってみました。
・LinkText.jsxを作成。
　また読み込み先に以下のようなコードを記述しました。
`<LinkText destination={"/todoregister"} linkName={"Todo登録"} />`

**Comment by mizushima1226** [comment]
良きと思います👍

これは好みで分かれるかもな話ですが、
linkNameでテキストを渡しているところ、childrenとして渡してあげると直感的に使えるコンポーネントになるかと思います〜

こんな感じです↓
```
<LinkText>Todo登録</LinkText>
```

**Comment by macmeals** [comment]
ご確認ありがとうございます👍
色々な書き方を勉強したいので、childrenで渡す方法で修正しました。以下が修正です。

LinkText.jsx
`<Link to={destination} state={{ state: linkState }} css={linkstyle}>
      {props.children}
    </Link>`
TodoRegister.jsx
`<LinkText destination={"/todolist"} linkState={incompleteTodos}>
        Todo一覧へ
      </LinkText>`
TodoList.jsx
`<LinkText destination={"/todoregister"}>Todo登録</LinkText>`

 destination,linkStateはPropsで渡しています。（これは渡さないといけない値かと思いました。）

**Comment by mizushima1226** [comment]
いい感じと思います👍
masterブランチにはまだ未反映でしょうか？👀
反映されこちらで一旦確認後、このissueはcloseしようかと思います！
